# Generated by Django 6.0 on 2025-12-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
