# Generated by Django 6.0 on 2025-12-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0003_users_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Chats.users'),
        ),
    ]
