# Generated by Django 6.0 on 2025-12-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0004_teachers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
